### ISSUE TITLE
Chart library usage

### ISSUE THREAD

**Issue by strepon** [Wicchi/weather_application#6]
It would be better to use the chart library from NPM package instead of loaded from CDN.

**Comment by strepon** [comment]
The chart library should be included into normal packages, not development - it is used for normal application run.

**Comment by Wicchi** [comment]
Not fully understand what do you want to?

**Comment by strepon** [comment]
I mean that the chart package should not be listed in `devDependencies` (installed by `npm install --save-dev`), but in `dependencies` (`npm install --save`) of package.json.

**Comment by Wicchi** [comment]
#8 done in last commit

**Comment by strepon** [comment]
`package-lock.json` should be updated as well, now it is not synchronized with `package.json`. This can be simply done by installing the package by npm install.

**Comment by strepon** [comment]
Perfect, done.
